# Generated by Django 4.2.1 on 2023-05-30 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_activity_pool_delete_post_activity_pools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='cost_per_hour',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='pools',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='location',
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pool',
            name='activities',
            field=models.ManyToManyField(to='blog.activity'),
        ),
        migrations.AddField(
            model_name='pool',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
